"""Shared authored opening interviews and victim profiles for campaign generators."""

VICTIM_PROFILES = {
    "murder_in_the_marigold_rooms": "Ambrose Vane expected the foundation accounts before dessert and had promised three different people a private decision. He was feared for making every favor feel like a debt; his empty chair leaves the club unsure which promises still bind.",
    "five_places_at_dinner": "Imogen Saye intended to announce a change in the foundation leadership after dinner. She habitually altered place cards herself when conversation mattered more than rank, so nobody agrees whether the final seating was accident, kindness, or warning.",
    "the_guest_in_suite_808": "Lucien Grey came to Halcyon seeking letters he said could free someone from an old obligation. He borrowed names as readily as rooms, but always signed for tea in his own slanted hand.",
    "the_sleeper_across_the_city": "Hugo Quill boarded intending to settle his foundation affairs before the train returned to the city. He traded seats and compartments impulsively, leaving each companion with a different expectation of their promised ten minutes.",
    "the_empty_carriage": "Mae Corbin planned to condemn the inspection carriage unless its unexplained movements were resolved that night. She checked defects with her own hands and left pencilled questions beside anything an official log made too tidy.",
    "the_ashes_of_blackthorn_lane": "Arun Black meant to publish corrected boundary figures in the morning. He was generous with access and merciless about attribution, leaving clients, colleagues, and rivals uncertain who would be named beside the new map.",
    "the_violinist_without_a_shadow": "Mara Quill was preparing to abandon the centre's gala program and play an unannounced work of her own. She repeated difficult passages without pause, but always stopped when the courtyard bell sounded.",
    "the_red_fog_of_south_quay": "Tomas Rell intended to shut the pumping station until its safety records were corrected. He trusted living sentinels more than alarm panels and fed the yard birds before every night inspection.",
    "the_final_cut": "Leon Pike came to the screening determined to restore a sequence the studio wanted removed. He argued in images, then waited through the entire reel before asking anyone for an answer.",
    "a_private_performance": "Simon Rusk planned to end Helena's residency after the public rehearsal. He interrupted performances only from the aisle and always waited for a phrase to finish before speaking.",
    "the_perfect_vintage": "Elise Marr intended to disclose that the cellar's celebrated inventory no longer matched its bottles. She remembered promises by the wine shared over them, making her judgment personal as well as professional.",
    "the_architects_model": "Amara Holt arrived to stop occupancy of Crest Tower until the unfinished edge was made safe. She marked discrepancies directly on models, then photographed the real site before anyone could revise the miniature.",
    "the_last_garden_prize": "Mara Voss planned to announce both the garden prize and the end of a grant partnership. She watered every entry herself after judging, a small ritual the exhibitors knew well enough to use as a clock.",
    "the_last_performance_at_bellwether_hall": "Celia North meant the hall's last rehearsal to become a public argument for saving it. She checked every cloth and cue herself, and had privately arranged to leave Bellwether after the final performance.",
    "a_recipe_for_silence": "Livia Stone intended to name the recipe she believed had been stolen before announcing a winner. She tasted in a fixed order, rinsed her own engraved spoon, and gave unsuccessful cooks the courtesy of a private explanation.",
    "death_on_the_promenade": "Owen Lark was due to challenge the redevelopment survey from the bandstand. His bright coat made him easy to follow, while his familiar uneven stride made him difficult for a neighbor to mistake.",
}

# Each answer establishes relationship and chronology without confronting evidence.
OPENINGS = {
    "clara": "Clara squares Ambrose's empty place with the table. 'He wanted the accounts before dessert. I told him the foundation could not be governed between courses.'",
    "basil": "Basil turns his signet inward. 'Ambrose asked what I meant to do without the west property. He enjoyed questions that already contained the humiliation.'",
    "sonia": "Sonia consults the bell sheet. 'He arrived at six thirty-eight, asked for three files, and rang twice for the dinner list. That was Ambrose in an impatient mood.'",
    "felix": "Felix looks toward Imogen's portrait. 'She said there would be an announcement after dessert. With Imogen, an announcement meant somebody's chair was about to move.'",
    "alma": "Alma touches the unused place card. 'She promised we would speak as family tonight. I was tired of being introduced as a beneficiary.'",
    "ren": "Ren counts backward through the courses. 'She changed nothing on my menu, but twice asked when the room would be empty. That was not a question about food.'",
    "estelle": "Estelle corrects the name on the register. 'Lucien arrived as Nico Grey and asked for the old purchase file. He wanted privacy, but he wanted an audience for what came after.'",
    "nico": "Nico watches the lift doors. 'Lucien borrowed my booking because he said one night under my name would settle both our debts. I last saw him take the key to 810.'",
    "priya": "Priya keeps a finger on the archive packet. 'He wanted a letter whose writer is still alive. I told him records do not become harmless merely because they are old.'",
    "vivian": "Vivian folds the timetable. 'Hugo promised each of us ten minutes before Union Depot. He treated a railway circuit as though it were a board agenda.'",
    "eamon": "Eamon turns a ticket sleeve over. 'He offered me a room exchange, then asked what proof I had brought. He expected publication more than danger.'",
    "leila": "Leila taps the lounge rhythm once. 'He asked me to sing at the foundation benefit again. I said no. We parted before Union Depot, without the quarrel he seemed to want.'",
    "galen_shore": "Galen studies Mae's pencilled defect list. 'She came to close the carriage, not inspect it. Once Mae wrote a question mark, somebody lost a shift.'",
    "tari_noll": "Tari gives the movement number first. 'Mae asked whether the carriage had travelled off-book. I told her to read the log. I last saw her climb aboard alone.'",
    "esme_park": "Esme aligns two photographs. 'Mae distrusted fleet numbers after the repaint. She asked me to preserve every scratch before maintenance touched the car.'",
    "cora_fen": "Cora traces a boundary on the desk. 'Arun meant to publish revised figures tomorrow. He called it a correction; half the lane would call it an accusation.'",
    "milo_venn": "Milo closes the sales ledger. 'Arun wanted his share and my customer names. Generosity ended wherever attribution began.'",
    "inez_ward": "Inez brushes dried soil from her note. 'He asked whether an old wall proved an old boundary. I left at six fifteen, after telling him history is rarely that obedient.'",
    "dorian_kest": "Dorian watches the empty stand. 'Mara meant to replace the gala program without permission. She wanted the audience to hear her, not the centre.'",
    "sel_vale": "Sel names the abandoned piece. 'She played it to prove she no longer needed anyone here. I left during the same eight bars she had repeated all afternoon.'",
    "pavel_orr": "Pavel checks the booking book. 'Mara asked who had reserved the hall after seven. I told her nobody, which was not quite the same as saying it was free.'",
    "asha_venn": "Asha reads Tomas's shutdown notice twice. 'He intended to close the station over incomplete safety records. He thought caution belonged to him alone.'",
    "kerr_moss": "Kerr inventories the panel lights. 'Tomas wanted my signature on the shutdown. I refused until I could test the relay, and he went inside without me.'",
    "lena_pike": "Lena counts the occupied cages. 'He fed the birds before entering the station. Tomas trusted an animal breathing normally more than any green lamp.'",
    "vera": "Vera looks toward the dead projector beam. 'Leon wanted the orchard restored to the final cut. He said we would watch the whole reel before either of us defended ourselves.'",
    "iris": "Iris names the reel by edge code. 'Leon asked me to verify which version entered the vault. He was worried about an alteration, not a screening.'",
    "mal": "Mal keeps his voice low. 'Leon stayed after the private audience left. He asked me to run the projector at full speed and keep the booth shut.'",
    "helena": "Helena marks an absent downbeat. 'Simon intended to end my residency after rehearsal. He promised to let the orchestra finish before he said it publicly.'",
    "oren": "Oren raises one finger for a rest. 'Simon asked for the revised contracts in private. He expected an argument, so he scheduled it between movements.'",
    "mina": "Mina studies the room tone. 'Simon asked me to preserve a clean recording. He thought somebody would later dispute what was said in the hall.'",
    "conrad": "Conrad straightens Elise's glass. 'She wanted a complete inventory before the hero bottle was opened. Elise could forgive a poor vintage, never a false label.'",
    "pia": "Pia recites the promised bottle. 'Elise asked for my private invoices. She knew stock had moved and meant to decide whether that was theft before dinner ended.'",
    "luca": "Luca tests the rack with both hands. 'She asked whether the third bay was safe. I said it would stand tonight. That answer is mine, however badly it ages.'",
    "julian": "Julian surveys the model. 'Amara arrived to stop occupancy. She saw danger in unfinished work and insult in anyone asking for another week.'",
    "nell": "Nell separates two report copies. 'Amara wanted the edge closed before morning. She asked me for the unsigned inspection because she already knew the official file was incomplete.'",
    "rafi": "Rafi gives the model version. 'She photographed the floor, then asked for yesterday's digital model. Amara never trusted a miniature without the site beside it.'",
    "jon_bell": "Jon removes a dead leaf from Mara's prize card. 'She meant to announce the grant decision after judging. Until then she wanted every plant treated as though it had won.'",
    "nadia_price": "Nadia rubs soil from her sleeve. 'Mara was ending our partnership. She still asked me to help with the final watering; that was how she made a wound look like a duty.'",
    "eli_ward": "Eli names Mara's newest cultivar. 'She could recognize another grower's cutting at ten paces. Tonight she said some prizes belonged to the people who did the work.'",
    "marcus_vale": "Marcus checks the rehearsal list. 'Celia wanted the final run exact before she made her speech for the hall. She had changed one backdrop and told nobody why.'",
    "ruth_anwar": "Ruth removes a pin from her cuff. 'Celia and I were leaving after the performance. She asked me to pack only what we could carry without help.'",
    "theo_marsh": "Theo taps the cue sequence. 'Celia checked every call herself. At the interval she said one cue in the book had become a lie.'",
    "adrian_moss": "Adrian polishes an already clean spoon. 'Livia promised to explain her decision before naming the winner. She believed disappointment should be served privately.'",
    "tessa_bloom": "Tessa sorts leaves by scent. 'Livia asked who had taught me the broth. She was not judging flavor by then; she was tracing ownership.'",
    "gabe_noor": "Gabe counts the tasting spoons. 'Livia rinsed her own engraved one between courses. She said shared tools made for shared excuses.'",
    "sabine_cross": "Sabine folds the festival map. 'Owen meant to challenge the survey from the bandstand. He wanted the neighborhood watching when the boundary moved back.'",
    "dario_finch": "Dario creases the notice again. 'Owen offered me until nine to admit the survey was wrong. After that he would make the argument public.'",
    "mei_rowan": "Mei watches the promenade above. 'Owen walked the route twice before every meeting. The old ankle injury shortened his right step; everyone here knew the rhythm.'",
}


def evidence_prompt(label: str) -> str:
    """Turn a clue label into an in-world confrontation rather than UI boilerplate."""
    return f"Then account for the {label.lower()}."
